version: '3.0'
services:
  query-builder-preprocessing:
    image: nlescstoryteller/query-builder-preprocessing
    environment:
      - KNOWLEDGE_STORE_SERVER_URL=${KNOWLEDGE_STORE_SERVER_URL}
    volumes:
      - data:/data

  query-builder-xenon:    
    image: nlescstoryteller/query-builder-xenon
    environment:
      - KNOWLEDGE_STORE_SERVER_URL=${KNOWLEDGE_STORE_SERVER_URL}
    restart: always
    volumes:
      - data:/data
    expose:
      - "4567"

  query-builder-server:
    image: nlescstoryteller/query-builder-server
    restart: always    
    expose:
      - "5000"
    volumes:
      - data:/data
    links:
      - query-builder-xenon:xenon

  query-builder-client:
    restart: always
    image: nlescstoryteller/query-builder-client
    ports:
      - "9000:9000"
    links:
      - query-builder-server:server

  uncertainty-visualization:
    restart: always
    image: nlescstoryteller/uncertainty-visualization
    ports:
      - "9001:9001"
    links:
      - query-builder-server:server

  nginx:
    build: nginx/
    ports:
      - "80:80"
    links:
      - query-builder-xenon
      - query-builder-server
      - query-builder-client
      - uncertainty-visualization

volumes:
  data:
    external:
      name: data
